### ISSUE TITLE
J3.12 connection issue

### ISSUE THREAD

**Issue by johanpeters** [akeeba/panopticon_connector_j3#6]
Hello,
i have 2 sites running Joomla 3.
1 site is working out of the box with Panaopticon, the other still does not want to connect.

i am running version 1.01 of panopticon and also the latest build of the agent.

try to connect failed.
checking .httaccess, SEF and rewriting.. tested with enabled and disabled.. stil not working
rename .httaccess, stil not working
set default template, stil not working

when i open the url domein.com/index.php//panopticon_api i got a general error on the site template. thats why i try'd the default joomla template, stil not working

when i open de url you get a error on the page, is that correct?.. also on the working J3 and J4 site.
perhaps a idea to create a page and not a 404 error.. or is there something wrong

i set debug on enabled and maximum.. on site and debug enabled on panoption. 
nothing special that make sense to me to give me a idea where the issue is.

disabled adminexile (administrator protection), same issue.

i don't have any options left to try (as far i can think of).
if needed i can arrange access for you.. 

thanks in advanced.. and yes, it needs to be upgraded to J4 or even J5. .but its a website of my sister and she needs time to think what she wants on the new site etc.. 
so, if this issue can not be resolved easy.. save yourself time developing panopticon and not to mutch time on this issue.

**Comment by nikosdion** [comment]
If you access index.php/panopticon_api you should get a 404 error. This is expected and as I have explained desirable because it prevents "dork attacks".

Make sure you have installed connector version 1.0.1 and double check the token.

**Comment by johanpeters** [comment]
> If you access index.php/panopticon_api you should get a 404 error. This is expected and as I have explained desirable because it prevents "dork attacks".
> 
> Make sure you have installed connector version 1.0.1 and double check the token.

i had already installed version 1.01 of the connector.. and i dubble checked the security token.
token is correct but still unable to connect

**Comment by nikosdion** [comment]
Email me the URL and the token.

**Comment by johanpeters** [comment]
> Email me the URL and the token.

i just  sent you a e-mail.

**Comment by nikosdion** [comment]
Your server closes the HTTP/2 connection prematurely, without returning the content. This is either an error from another extension, or a problem with the server itself. I can't tell which one. You should ask your host to check the error logs when they run `curl "https://www.example.com/index.php/panopticon_api" -H "X=Joomla-Token: YOUR_TOKEN" -H "Accept: application/vnd.api+json"` where https://www.example.com is your site and YOUR_TOKEN is your API token (the information you sent me in your email).

**Comment by johanpeters** [comment]
okay.. thanks for the update.. i will check with the hoster to see.. 
and i will make a copy to my own server to see if its site related or server related.

i will update this issue when i have any news / updates / etc.
