### ISSUE TITLE
Panopticon 1.1.0 cannot connect to J3 connector 1.0.3

### ISSUE THREAD

**Issue by GJSchaller** [akeeba/panopticon_connector_j3#9]
I have a legacy J3 site I need to maintain until the last Component is J4 & 5 ready.  I recently set up Panopticon, and it is currently on version 1.1.0.  I was able to add my J4 & 5 sites without issue - so far, so good.

When I attempted to add my J3 site using the Connector version 1.0.3, Panopticon was unable to communicate with the site.  I uninstalled, and installed v1.0 - that worked, and I was able to establish the connection.

When I updated the connector to 1.0.3 on the Joomla site, the connection broke again.  I reverted back to 1.0, and it's working now.

I have a clone of the site I am using for testing, so I can work with that to test updates to the connector or other settings as needed.

**Comment by GJSchaller** [comment]
As a test, I manually installed the updates, from 1.0.0 up to 1.0.3.  When I installed 1.0.2, the connection broke as well.

**Comment by nikosdion** [comment]
Try using version 1.0.4.

**Comment by GJSchaller** [comment]
Works perfect, and the Akeeba Backup connector is working now too - thank you, very much!

**Comment by nikosdion** [comment]
You're welcome!
